########################################################
#                 Config de depuración                 #
#                                                      #
# la config no es usada por MySaml core por el momento #
########################################################
ErrorLog: true